// 토스페이먼츠 은행 코드 (2자리). 가상계좌 환불 시 환불받을 계좌 은행으로 사용한다.
// 표준 은행코드(banks.data.json, 3자리)와 다른 체계이므로 환불에는 반드시 이 목록을 사용한다.
export const TOSS_BANKS: { code: string; name: string }[] = [
  { code: "06", name: "국민은행" },
  { code: "88", name: "신한은행" },
  { code: "20", name: "우리은행" },
  { code: "81", name: "하나은행" },
  { code: "11", name: "농협은행(NH)" },
  { code: "03", name: "기업은행(IBK)" },
  { code: "90", name: "카카오뱅크" },
  { code: "92", name: "토스뱅크" },
  { code: "89", name: "케이뱅크" },
  { code: "02", name: "산업은행(KDB)" },
  { code: "07", name: "수협은행" },
  { code: "23", name: "SC제일은행" },
  { code: "27", name: "씨티은행" },
  { code: "31", name: "대구은행(iM)" },
  { code: "32", name: "부산은행" },
  { code: "34", name: "광주은행" },
  { code: "35", name: "제주은행" },
  { code: "37", name: "전북은행" },
  { code: "39", name: "경남은행" },
  { code: "12", name: "단위농협(지역농축협)" },
  { code: "45", name: "새마을금고" },
  { code: "48", name: "신협" },
  { code: "50", name: "저축은행" },
  { code: "71", name: "우체국" },
]
