/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
/* biome-ignore-all lint: auto-generated */

declare module "sst" {
  export interface Resource {
    "AuthSecret": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "Cafe24ClientId": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "Cafe24ClientSecret": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "Cafe24ServiceKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "JwtRefreshSecret": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "JwtVerificationTokenSecret": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "KafkaApiKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "KafkaApiSecret": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "KakaoClientId": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "KakaoClientSecret": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "TwilioAccountSid": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "TwilioAuthToken": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "UserService": {
      "service": string
      "type": "sst.aws.Service"
      "url": string
    }
    "UserServiceDatabaseUrl": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "Vpc": {
      "type": "sst.aws.Vpc"
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}