export const ORDER_EVENTS = {
  CREATED: 'ORDER_CREATED',
  CONFIRMED: 'ORDER_CONFIRMED',
  MODIFIED: 'ORDER_MODIFIED',
  CANCELLED: 'ORDER_CANCELLED',
} as const;

export const FULFILLMENT_EVENTS = {
  CREATED: 'FULFILLMENT_CREATED',
  READY: 'FULFILLMENT_READY',
  LABELLED: 'FULFILLMENT_LABELLED',
  SHIPPED: 'FULFILLMENT_SHIPPED',
  CANCELLED: 'FULFILLMENT_CANCELLED',
} as const;

export type OrderEvent = typeof ORDER_EVENTS[keyof typeof ORDER_EVENTS];
export type FulfillmentEvent = typeof FULFILLMENT_EVENTS[keyof typeof FULFILLMENT_EVENTS];


