export enum ErrorCode {
  VALIDATION_INVALID_AMOUNT = 'VALIDATION_INVALID_AMOUNT',
  VALIDATION_MISSING_FIELD = 'VALIDATION_MISSING_FIELD',

  PG_TIMEOUT = 'PG_TIMEOUT',
  PG_DECLINED = 'PG_DECLINED',
  PG_UNKNOWN_ERROR = 'PG_UNKNOWN_ERROR',

  PAYMENT_NOT_FOUND = 'PAYMENT_NOT_FOUND',
  PAYMENT_ALREADY_CAPTURED = 'PAYMENT_ALREADY_CAPTURED',

  IDEMPOTENCY_CONFLICT = 'IDEMPOTENCY_CONFLICT',
  DATABASE_ERROR = 'DATABASE_ERROR',
}
