import { z } from 'zod';
import type { Scenario } from '../types';

// Fixed file IDs for deterministic test runs
const MOCK_FILE_IDS = {
  pc_main_01: '01933e7a-1234-7000-a000-000000000001',
  mobile_main_01: '01933e7a-1234-7000-a000-000000000002',
  pc_main_02: '01933e7a-1234-7000-a000-000000000003',
  mobile_main_02: '01933e7a-1234-7000-a000-000000000004',
  pc_sec_01: '01933e7a-1234-7000-a000-000000000005',
  mobile_sec_01: '01933e7a-1234-7000-a000-000000000006',
  pc_sec_02: '01933e7a-1234-7000-a000-000000000007',
  mobile_sec_02: '01933e7a-1234-7000-a000-000000000008',
};

export const bannerScenarios: Scenario[] = [
  {
    id: 'BANNER-001',
    name: '배너 그룹 기본 CRUD',
    category: 'PIM > Banners',
    validation: '배너 그룹의 생성, 조회, 수정, 삭제 전체 플로우 확인',
    steps: [
      {
        id: 'create-banner-group',
        method: 'POST',
        path: '/banner-groups',
        body: {
          code: 'MAIN-BANNER-{{timestamp}}',
          title: '메인 배너',
          category: 'main',
          pcWidth: 1920,
          pcHeight: 600,
          mobileWidth: 768,
          mobileHeight: 400,
          description: '메인 페이지 배너 그룹',
          isActive: true,
          sortOrder: 1,
        },
        expectedStatus: 201,
        description: '배너 그룹 생성',
        extractFromResponse: {
          bannerGroupId: 'id',
        },
        responseSchema: z.object({
          id: z.string().uuid(),
          code: z.string(),
          title: z.string(),
          category: z.string(),
          isActive: z.boolean(),
          sortOrder: z.number(),
        }),
      },
      {
        id: 'get-banner-group',
        method: 'GET',
        path: '/banner-groups/{{bannerGroupId}}',
        expectedStatus: 200,
        description: '생성된 배너 그룹 조회',
        responseSchema: z.object({
          id: z.string().uuid(),
          code: z.string(),
          title: z.literal('메인 배너'),
          category: z.literal('main'),
          pcWidth: z.literal(1920),
          pcHeight: z.literal(600),
          mobileWidth: z.literal(768),
          mobileHeight: z.literal(400),
          isActive: z.literal(true),
          sortOrder: z.literal(1),
        }),
      },
      {
        id: 'update-banner-group',
        method: 'PUT',
        path: '/banner-groups/{{bannerGroupId}}',
        body: {
          title: '메인 배너 (수정됨)',
          sortOrder: 10,
        },
        expectedStatus: 200,
        description: '배너 그룹 수정',
      },
      {
        id: 'verify-update',
        method: 'GET',
        path: '/banner-groups/{{bannerGroupId}}',
        expectedStatus: 200,
        description: '수정 확인',
        responseSchema: z.object({
          title: z.literal('메인 배너 (수정됨)'),
          sortOrder: z.literal(10),
        }),
      },
      {
        id: 'delete-banner-group',
        method: 'DELETE',
        path: '/banner-groups/{{bannerGroupId}}',
        expectedStatus: 200,
        description: '배너 그룹 삭제 (Soft Delete)',
      },
      {
        id: 'verify-delete',
        method: 'GET',
        path: '/banner-groups/{{bannerGroupId}}',
        expectedStatus: 404,
        description: '삭제 확인 (404 예상)',
      },
    ],
  },

  {
    id: 'BANNER-002',
    name: '코드로 배너 그룹 조회 (활성 배너 포함)',
    category: 'PIM > Banners',
    validation: 'GET /banner-groups/by-code/:code 엔드포인트로 배너 그룹과 활성 배너 목록 조회',
    steps: [
      {
        id: 'create-group',
        method: 'POST',
        path: '/banner-groups',
        body: {
          code: 'PROMO-{{timestamp}}',
          title: '프로모션 배너',
          category: 'promotion',
          isActive: true,
          sortOrder: 1,
        },
        expectedStatus: 201,
        description: '배너 그룹 생성',
        extractFromResponse: {
          groupId: 'id',
          groupCode: 'code',
        },
      },
      {
        id: 'create-active-banner',
        method: 'POST',
        path: '/banners',
        body: {
          bannerGroupId: '{{groupId}}',
          title: '활성 배너',
          pcImageFileId: MOCK_FILE_IDS.pc_main_01,
          mobileImageFileId: MOCK_FILE_IDS.mobile_main_01,
          isActive: true,
          sortOrder: 1,
        },
        expectedStatus: 201,
        description: '활성 배너 생성',
      },
      {
        id: 'create-inactive-banner',
        method: 'POST',
        path: '/banners',
        body: {
          bannerGroupId: '{{groupId}}',
          title: '비활성 배너',
          pcImageFileId: MOCK_FILE_IDS.pc_main_02,
          mobileImageFileId: MOCK_FILE_IDS.mobile_main_02,
          isActive: false,
          sortOrder: 2,
        },
        expectedStatus: 201,
        description: '비활성 배너 생성',
      },
      {
        id: 'get-by-code',
        method: 'GET',
        path: '/banner-groups/by-code/{{groupCode}}',
        expectedStatus: 200,
        description: '코드로 배너 그룹 조회 (활성 배너만 포함)',
        responseSchema: z.object({
          id: z.string().uuid(),
          code: z.string(),
          title: z.literal('프로모션 배너'),
          banners: z.array(z.any()).length(1), // 활성 배너만
        }),
      },
    ],
  },

  {
    id: 'BANNER-003',
    name: '배너 CRUD (그룹 내)',
    category: 'PIM > Banners',
    validation: '배너의 생성, 조회, 수정, 삭제 플로우 확인',
    steps: [
      {
        id: 'create-group',
        method: 'POST',
        path: '/banner-groups',
        body: {
          code: 'EVENT-{{timestamp}}',
          title: '이벤트 배너',
          category: 'event',
          isActive: true,
        },
        expectedStatus: 201,
        description: '배너 그룹 생성',
        extractFromResponse: {
          groupId: 'id',
        },
      },
      {
        id: 'create-banner',
        method: 'POST',
        path: '/banners',
        body: {
          bannerGroupId: '{{groupId}}',
          title: '신규 이벤트',
          description: '신규 회원 할인 이벤트',
          pcImageFileId: MOCK_FILE_IDS.pc_main_01,
          mobileImageFileId: MOCK_FILE_IDS.mobile_main_01,
          linkUrl: 'https://example.com/event',
          isActive: true,
          sortOrder: 1,
        },
        expectedStatus: 201,
        description: '배너 생성',
        extractFromResponse: {
          bannerId: 'id',
        },
        responseSchema: z.object({
          id: z.string().uuid(),
          bannerGroupId: z.string().uuid(),
          title: z.string(),
          isActive: z.boolean(),
        }),
      },
      {
        id: 'get-banner',
        method: 'GET',
        path: '/banners/{{bannerId}}',
        expectedStatus: 200,
        description: '생성된 배너 조회',
        responseSchema: z.object({
          id: z.string().uuid(),
          title: z.literal('신규 이벤트'),
          linkUrl: z.literal('https://example.com/event'),
          isActive: z.literal(true),
        }),
      },
      {
        id: 'update-banner',
        method: 'PUT',
        path: '/banners/{{bannerId}}',
        body: {
          title: '신규 이벤트 (연장)',
          description: '이벤트 기간 연장',
          linkUrl: 'https://example.com/event-extended',
        },
        expectedStatus: 200,
        description: '배너 수정',
      },
      {
        id: 'verify-update',
        method: 'GET',
        path: '/banners/{{bannerId}}',
        expectedStatus: 200,
        description: '수정 확인',
        responseSchema: z.object({
          title: z.literal('신규 이벤트 (연장)'),
          linkUrl: z.literal('https://example.com/event-extended'),
        }),
      },
      {
        id: 'delete-banner',
        method: 'DELETE',
        path: '/banners/{{bannerId}}',
        expectedStatus: 200,
        description: '배너 삭제 (Soft Delete)',
      },
      {
        id: 'verify-delete',
        method: 'GET',
        path: '/banners/{{bannerId}}',
        expectedStatus: 404,
        description: '삭제 확인 (404 예상)',
      },
    ],
  },

  {
    id: 'BANNER-004',
    name: '배너 목록 조회 (includeInactive 파라미터)',
    category: 'PIM > Banners',
    validation: 'includeInactive 쿼리 파라미터로 비활성 배너 포함 조회',
    steps: [
      {
        id: 'create-group',
        method: 'POST',
        path: '/banner-groups',
        body: {
          code: 'TEST-{{timestamp}}',
          title: '테스트 배너 그룹',
          category: 'test',
          isActive: true,
        },
        expectedStatus: 201,
        description: '배너 그룹 생성',
        extractFromResponse: {
          groupId: 'id',
        },
      },
      {
        id: 'create-active-banner',
        method: 'POST',
        path: '/banners',
        body: {
          bannerGroupId: '{{groupId}}',
          title: '활성 배너',
          pcImageFileId: MOCK_FILE_IDS.pc_main_01,
          mobileImageFileId: MOCK_FILE_IDS.mobile_main_01,
          isActive: true,
          sortOrder: 1,
        },
        expectedStatus: 201,
        description: '활성 배너 생성',
      },
      {
        id: 'create-inactive-banner',
        method: 'POST',
        path: '/banners',
        body: {
          bannerGroupId: '{{groupId}}',
          title: '비활성 배너',
          pcImageFileId: MOCK_FILE_IDS.pc_main_02,
          mobileImageFileId: MOCK_FILE_IDS.mobile_main_02,
          isActive: false,
          sortOrder: 2,
        },
        expectedStatus: 201,
        description: '비활성 배너 생성',
      },
      {
        id: 'list-active-only',
        method: 'GET',
        path: '/banners/by-group/{{groupId}}',
        expectedStatus: 200,
        description: '활성 배너만 조회 (기본)',
        responseSchema: z.array(z.any()).length(1),
      },
      {
        id: 'list-include-inactive',
        method: 'GET',
        path: '/banners/by-group/{{groupId}}',
        queryParams: {
          includeInactive: 'true',
        },
        expectedStatus: 200,
        description: '비활성 배너 포함 조회',
        responseSchema: z.array(z.any()).length(2),
      },
    ],
  },

  {
    id: 'BANNER-005',
    name: '배너 표시 기간 필터링',
    category: 'PIM > Banners',
    validation: 'displayStartAt/displayEndAt 기반 배너 표시 여부 확인',
    steps: [
      {
        id: 'create-group',
        method: 'POST',
        path: '/banner-groups',
        body: {
          code: 'PERIOD-{{timestamp}}',
          title: '기간 제한 배너',
          category: 'timed',
          isActive: true,
        },
        expectedStatus: 201,
        description: '배너 그룹 생성',
        extractFromResponse: {
          groupId: 'id',
          groupCode: 'code',
        },
      },
      {
        id: 'create-future-banner',
        method: 'POST',
        path: '/banners',
        body: {
          bannerGroupId: '{{groupId}}',
          title: '미래 배너',
          pcImageFileId: MOCK_FILE_IDS.pc_main_01,
          mobileImageFileId: MOCK_FILE_IDS.mobile_main_01,
          displayStartAt: '2030-01-01T00:00:00Z',
          displayEndAt: '2030-12-31T23:59:59Z',
          isActive: true,
          sortOrder: 1,
        },
        expectedStatus: 201,
        description: '미래 표시 배너 생성',
      },
      {
        id: 'create-expired-banner',
        method: 'POST',
        path: '/banners',
        body: {
          bannerGroupId: '{{groupId}}',
          title: '만료된 배너',
          pcImageFileId: MOCK_FILE_IDS.pc_main_02,
          mobileImageFileId: MOCK_FILE_IDS.mobile_main_02,
          displayStartAt: '2020-01-01T00:00:00Z',
          displayEndAt: '2021-12-31T23:59:59Z',
          isActive: true,
          sortOrder: 2,
        },
        expectedStatus: 201,
        description: '만료된 배너 생성',
      },
      {
        id: 'create-active-banner',
        method: 'POST',
        path: '/banners',
        body: {
          bannerGroupId: '{{groupId}}',
          title: '현재 표시 배너',
          pcImageFileId: MOCK_FILE_IDS.pc_sec_01,
          mobileImageFileId: MOCK_FILE_IDS.mobile_sec_01,
          displayStartAt: '2020-01-01T00:00:00Z',
          displayEndAt: '2030-12-31T23:59:59Z',
          isActive: true,
          sortOrder: 3,
        },
        expectedStatus: 201,
        description: '현재 표시 중인 배너 생성',
      },
      {
        id: 'get-by-code-filtered',
        method: 'GET',
        path: '/banner-groups/by-code/{{groupCode}}',
        expectedStatus: 200,
        description: '코드로 조회 (현재 시점에 표시 가능한 배너만)',
        responseSchema: z.object({
          banners: z.array(
            z.object({
              title: z.string(),
            })
          ),
        }),
      },
    ],
  },

  {
    id: 'BANNER-006',
    name: '배너 그룹 카테고리 필터링',
    category: 'PIM > Banners',
    validation: 'GET /banner-groups에서 category 쿼리 파라미터로 필터링',
    steps: [
      {
        id: 'create-main-group',
        method: 'POST',
        path: '/banner-groups',
        body: {
          code: 'MAIN-{{timestamp}}',
          title: '메인 배너 그룹',
          category: 'main',
          isActive: true,
        },
        expectedStatus: 201,
        description: 'main 카테고리 그룹 생성',
      },
      {
        id: 'create-sub-group',
        method: 'POST',
        path: '/banner-groups',
        body: {
          code: 'SUB-{{timestamp}}',
          title: '서브 배너 그룹',
          category: 'sub',
          isActive: true,
        },
        expectedStatus: 201,
        description: 'sub 카테고리 그룹 생성',
      },
      {
        id: 'list-all',
        method: 'GET',
        path: '/banner-groups',
        expectedStatus: 200,
        description: '전체 배너 그룹 조회',
        responseSchema: z.array(z.any()).min(2),
      },
      {
        id: 'list-main-only',
        method: 'GET',
        path: '/banner-groups',
        queryParams: {
          category: 'main',
        },
        expectedStatus: 200,
        description: 'main 카테고리만 조회',
        responseSchema: z.array(
          z.object({
            category: z.literal('main'),
          })
        ),
      },
    ],
  },

  {
    id: 'BANNER-007',
    name: '정렬 순서 검증',
    category: 'PIM > Banners',
    validation: 'sortOrder 필드에 따른 배너 정렬 확인',
    steps: [
      {
        id: 'create-group',
        method: 'POST',
        path: '/banner-groups',
        body: {
          code: 'SORT-{{timestamp}}',
          title: '정렬 테스트 그룹',
          category: 'test',
          isActive: true,
        },
        expectedStatus: 201,
        description: '배너 그룹 생성',
        extractFromResponse: {
          groupId: 'id',
        },
      },
      {
        id: 'create-banner-3',
        method: 'POST',
        path: '/banners',
        body: {
          bannerGroupId: '{{groupId}}',
          title: '배너 3',
          pcImageFileId: MOCK_FILE_IDS.pc_main_01,
          mobileImageFileId: MOCK_FILE_IDS.mobile_main_01,
          isActive: true,
          sortOrder: 3,
        },
        expectedStatus: 201,
        description: 'sortOrder 3인 배너 생성',
      },
      {
        id: 'create-banner-1',
        method: 'POST',
        path: '/banners',
        body: {
          bannerGroupId: '{{groupId}}',
          title: '배너 1',
          pcImageFileId: MOCK_FILE_IDS.pc_main_02,
          mobileImageFileId: MOCK_FILE_IDS.mobile_main_02,
          isActive: true,
          sortOrder: 1,
        },
        expectedStatus: 201,
        description: 'sortOrder 1인 배너 생성',
      },
      {
        id: 'create-banner-2',
        method: 'POST',
        path: '/banners',
        body: {
          bannerGroupId: '{{groupId}}',
          title: '배너 2',
          pcImageFileId: MOCK_FILE_IDS.pc_sec_01,
          mobileImageFileId: MOCK_FILE_IDS.mobile_sec_01,
          isActive: true,
          sortOrder: 2,
        },
        expectedStatus: 201,
        description: 'sortOrder 2인 배너 생성',
      },
      {
        id: 'list-sorted',
        method: 'GET',
        path: '/banners/by-group/{{groupId}}',
        expectedStatus: 200,
        description: '정렬된 배너 목록 조회',
        responseSchema: z
          .array(
            z.object({
              title: z.string(),
              sortOrder: z.number(),
            })
          )
          .length(3),
      },
    ],
  },

  {
    id: 'BANNER-008',
    name: '배너 그룹 삭제 시 하위 배너 연쇄 삭제',
    category: 'PIM > Banners',
    validation: '배너 그룹 삭제 시 하위 배너들도 함께 soft delete되는지 확인',
    steps: [
      {
        id: 'create-group',
        method: 'POST',
        path: '/banner-groups',
        body: {
          code: 'CASCADE-{{timestamp}}',
          title: '연쇄 삭제 테스트',
          category: 'test',
          isActive: true,
        },
        expectedStatus: 201,
        description: '배너 그룹 생성',
        extractFromResponse: {
          groupId: 'id',
        },
      },
      {
        id: 'create-banner-1',
        method: 'POST',
        path: '/banners',
        body: {
          bannerGroupId: '{{groupId}}',
          title: '하위 배너 1',
          pcImageFileId: MOCK_FILE_IDS.pc_main_01,
          mobileImageFileId: MOCK_FILE_IDS.mobile_main_01,
          isActive: true,
        },
        expectedStatus: 201,
        description: '배너 1 생성',
        extractFromResponse: {
          banner1Id: 'id',
        },
      },
      {
        id: 'create-banner-2',
        method: 'POST',
        path: '/banners',
        body: {
          bannerGroupId: '{{groupId}}',
          title: '하위 배너 2',
          pcImageFileId: MOCK_FILE_IDS.pc_main_02,
          mobileImageFileId: MOCK_FILE_IDS.mobile_main_02,
          isActive: true,
        },
        expectedStatus: 201,
        description: '배너 2 생성',
        extractFromResponse: {
          banner2Id: 'id',
        },
      },
      {
        id: 'delete-group',
        method: 'DELETE',
        path: '/banner-groups/{{groupId}}',
        expectedStatus: 200,
        description: '배너 그룹 삭제',
      },
      {
        id: 'verify-group-deleted',
        method: 'GET',
        path: '/banner-groups/{{groupId}}',
        expectedStatus: 404,
        description: '배너 그룹 삭제 확인',
      },
      {
        id: 'verify-banner1-deleted',
        method: 'GET',
        path: '/banners/{{banner1Id}}',
        expectedStatus: 404,
        description: '하위 배너 1 삭제 확인',
      },
      {
        id: 'verify-banner2-deleted',
        method: 'GET',
        path: '/banners/{{banner2Id}}',
        expectedStatus: 404,
        description: '하위 배너 2 삭제 확인',
      },
    ],
  },

  {
    id: 'BANNER-009',
    name: '상품 마스터 연결 배너',
    category: 'PIM > Banners',
    validation: 'linkedProductMasterIds를 통한 상품 연결 기능 확인',
    steps: [
      {
        id: 'create-product-1',
        method: 'POST',
        path: '/masters',
        body: {},
        expectedStatus: 201,
        description: '상품 마스터 1 생성',
        extractFromResponse: {
          product1Id: 'masterId',
        },
      },
      {
        id: 'create-product-2',
        method: 'POST',
        path: '/masters',
        body: {},
        expectedStatus: 201,
        description: '상품 마스터 2 생성',
        extractFromResponse: {
          product2Id: 'masterId',
        },
      },
      {
        id: 'create-group',
        method: 'POST',
        path: '/banner-groups',
        body: {
          code: 'PRODUCT-{{timestamp}}',
          title: '상품 연결 배너',
          category: 'product',
          isActive: true,
        },
        expectedStatus: 201,
        description: '배너 그룹 생성',
        extractFromResponse: {
          groupId: 'id',
        },
      },
      {
        id: 'create-banner-with-products',
        method: 'POST',
        path: '/banners',
        body: {
          bannerGroupId: '{{groupId}}',
          title: '상품 프로모션',
          pcImageFileId: MOCK_FILE_IDS.pc_main_01,
          mobileImageFileId: MOCK_FILE_IDS.mobile_main_01,
          linkedProductMasterIds: ['{{product1Id}}', '{{product2Id}}'],
          isActive: true,
        },
        expectedStatus: 201,
        description: '상품 연결 배너 생성',
        extractFromResponse: {
          bannerId: 'id',
        },
      },
      {
        id: 'get-banner-with-products',
        method: 'GET',
        path: '/banners/{{bannerId}}',
        expectedStatus: 200,
        description: '배너 조회 및 연결된 상품 확인',
        responseSchema: z.object({
          id: z.string().uuid(),
          linkedProductMasterIds: z.array(z.string()).length(2),
        }),
      },
      {
        id: 'update-linked-products',
        method: 'PUT',
        path: '/banners/{{bannerId}}',
        body: {
          linkedProductMasterIds: ['{{product1Id}}'],
        },
        expectedStatus: 200,
        description: '연결 상품 수정',
      },
      {
        id: 'verify-updated-products',
        method: 'GET',
        path: '/banners/{{bannerId}}',
        expectedStatus: 200,
        description: '수정된 연결 상품 확인',
        responseSchema: z.object({
          linkedProductMasterIds: z.array(z.string()).length(1),
        }),
      },
    ],
  },

  {
    id: 'BANNER-010',
    name: 'PC/Mobile 이미지 크기 설정',
    category: 'PIM > Banners',
    validation: '배너 그룹의 PC/Mobile 이미지 크기 설정 확인',
    steps: [
      {
        id: 'create-group-with-dimensions',
        method: 'POST',
        path: '/banner-groups',
        body: {
          code: 'DIMENSION-{{timestamp}}',
          title: '크기 지정 배너',
          category: 'sized',
          pcWidth: 1920,
          pcHeight: 600,
          mobileWidth: 768,
          mobileHeight: 400,
          isActive: true,
        },
        expectedStatus: 201,
        description: '크기 정보 포함 배너 그룹 생성',
        extractFromResponse: {
          groupId: 'id',
        },
        responseSchema: z.object({
          pcWidth: z.literal(1920),
          pcHeight: z.literal(600),
          mobileWidth: z.literal(768),
          mobileHeight: z.literal(400),
        }),
      },
      {
        id: 'update-dimensions',
        method: 'PUT',
        path: '/banner-groups/{{groupId}}',
        body: {
          pcWidth: 2560,
          pcHeight: 800,
          mobileWidth: 1024,
          mobileHeight: 500,
        },
        expectedStatus: 200,
        description: '크기 정보 수정',
      },
      {
        id: 'verify-dimensions',
        method: 'GET',
        path: '/banner-groups/{{groupId}}',
        expectedStatus: 200,
        description: '수정된 크기 정보 확인',
        responseSchema: z.object({
          pcWidth: z.literal(2560),
          pcHeight: z.literal(800),
          mobileWidth: z.literal(1024),
          mobileHeight: z.literal(500),
        }),
      },
    ],
  },

  {
    id: 'BANNER-011',
    name: '에러: 중복 코드',
    category: 'PIM > Banners',
    validation: '배너 그룹 생성 시 중복 코드 에러 처리 확인',
    steps: [
      {
        id: 'create-first-group',
        method: 'POST',
        path: '/banner-groups',
        body: {
          code: 'DUPLICATE-CODE',
          title: '첫 번째 그룹',
          category: 'test',
          isActive: true,
        },
        expectedStatus: 201,
        description: '첫 번째 배너 그룹 생성',
      },
      {
        id: 'create-duplicate-group',
        method: 'POST',
        path: '/banner-groups',
        body: {
          code: 'DUPLICATE-CODE',
          title: '중복 코드 그룹',
          category: 'test',
          isActive: true,
        },
        expectedStatus: 400,
        description: '중복 코드로 생성 시도 (400 또는 409 예상)',
      },
    ],
  },

  {
    id: 'BANNER-012',
    name: '에러: 잘못된 그룹 ID',
    category: 'PIM > Banners',
    validation: '존재하지 않는 배너 그룹 ID로 배너 생성 시 에러 처리',
    steps: [
      {
        id: 'create-banner-invalid-group',
        method: 'POST',
        path: '/banners',
        body: {
          bannerGroupId: '00000000-0000-0000-0000-000000000000',
          title: '잘못된 그룹 배너',
          pcImageFileId: MOCK_FILE_IDS.pc_main_01,
          mobileImageFileId: MOCK_FILE_IDS.mobile_main_01,
          isActive: true,
        },
        expectedStatus: 404,
        description: '존재하지 않는 그룹 ID로 배너 생성 시도 (404 예상)',
      },
    ],
  },

  {
    id: 'BANNER-013',
    name: '완전한 배너 워크플로우',
    category: 'PIM > Banners',
    validation: '배너 그룹 및 배너의 전체 생명주기 테스트',
    steps: [
      {
        id: 'create-group',
        method: 'POST',
        path: '/banner-groups',
        body: {
          code: 'WORKFLOW-{{timestamp}}',
          title: '워크플로우 테스트',
          category: 'complete',
          pcWidth: 1920,
          pcHeight: 600,
          mobileWidth: 768,
          mobileHeight: 400,
          isActive: true,
          sortOrder: 1,
        },
        expectedStatus: 201,
        description: '배너 그룹 생성',
        extractFromResponse: {
          groupId: 'id',
          groupCode: 'code',
        },
      },
      {
        id: 'create-product',
        method: 'POST',
        path: '/masters',
        body: {},
        expectedStatus: 201,
        description: '연결할 상품 생성',
        extractFromResponse: {
          productId: 'masterId',
        },
      },
      {
        id: 'create-banner-full',
        method: 'POST',
        path: '/banners',
        body: {
          bannerGroupId: '{{groupId}}',
          title: '완전한 배너',
          description: '모든 필드 포함',
          pcImageFileId: MOCK_FILE_IDS.pc_main_01,
          mobileImageFileId: MOCK_FILE_IDS.mobile_main_01,
          linkUrl: 'https://example.com',
          linkedProductMasterIds: ['{{productId}}'],
          displayStartAt: '2020-01-01T00:00:00Z',
          displayEndAt: '2030-12-31T23:59:59Z',
          isActive: true,
          sortOrder: 1,
        },
        expectedStatus: 201,
        description: '완전한 배너 생성',
        extractFromResponse: {
          bannerId: 'id',
        },
      },
      {
        id: 'get-banner',
        method: 'GET',
        path: '/banners/{{bannerId}}',
        expectedStatus: 200,
        description: '배너 상세 조회',
        responseSchema: z.object({
          id: z.string().uuid(),
          bannerGroupId: z.string().uuid(),
          title: z.string(),
          description: z.string().nullable(),
          pcImageFileId: z.string(),
          mobileImageFileId: z.string(),
          linkUrl: z.string().nullable(),
          linkedProductMasterIds: z.array(z.string()).nullable(),
          displayStartAt: z.string().nullable(),
          displayEndAt: z.string().nullable(),
          isActive: z.boolean(),
          sortOrder: z.number(),
        }),
      },
      {
        id: 'list-by-group',
        method: 'GET',
        path: '/banners/by-group/{{groupId}}',
        expectedStatus: 200,
        description: '그룹별 배너 목록 조회',
        responseSchema: z.array(z.any()).min(1),
      },
      {
        id: 'get-by-code',
        method: 'GET',
        path: '/banner-groups/by-code/{{groupCode}}',
        expectedStatus: 200,
        description: '코드로 그룹 조회 (배너 포함)',
        responseSchema: z.object({
          id: z.string().uuid(),
          code: z.string(),
          banners: z.array(z.any()).min(1),
        }),
      },
      {
        id: 'list-groups',
        method: 'GET',
        path: '/banner-groups',
        expectedStatus: 200,
        description: '배너 그룹 목록 조회',
        responseSchema: z.array(z.any()).min(1),
      },
      {
        id: 'update-banner',
        method: 'PUT',
        path: '/banners/{{bannerId}}',
        body: {
          title: '수정된 배너',
          isActive: false,
        },
        expectedStatus: 200,
        description: '배너 수정',
      },
      {
        id: 'update-group',
        method: 'PUT',
        path: '/banner-groups/{{groupId}}',
        body: {
          title: '수정된 그룹',
        },
        expectedStatus: 200,
        description: '배너 그룹 수정',
      },
      {
        id: 'delete-banner',
        method: 'DELETE',
        path: '/banners/{{bannerId}}',
        expectedStatus: 200,
        description: '배너 삭제',
      },
      {
        id: 'delete-group',
        method: 'DELETE',
        path: '/banner-groups/{{groupId}}',
        expectedStatus: 200,
        description: '배너 그룹 삭제',
      },
    ],
  },
];
