import { z } from 'zod';
import type { Scenario } from '../types.ts';

/**
 * Channel Integration Test Scenarios
 *
 * Combined workflows testing Channel Products + Channel Listings together
 *
 * Total Scenarios: 2
 */

export const channelIntegrationScenarios: Scenario[] = [
  {
    id: 'CHINT-001',
    name: '전체 채널 제품 등록 플로우',
    category: 'PIM > Channel Integration',
    validation: 'Channel Products + Listings 통합 워크플로우 확인',
    steps: [
      {
        id: 'create-master',
        method: 'POST',
        path: '/masters',
        service: 'pim',
        body: {},
        expectedStatus: 201,
        description: '상품 마스터 생성',
        extractFromResponse: { masterId: 'masterId', versionId: 'id' },
      },
      {
        id: 'add-options',
        method: 'PUT',
        path: '/masters/{{masterId}}/versions/{{versionId}}',
        service: 'pim',
        body: {
          name: 'Integration Test Product {{timestamp}}',
          optionDiff: {
            add: [
              {
                displayName: '색상',
                sortOrder: 0,
                values: [
                  { displayName: '빨강', sortOrder: 1 },
                  { displayName: '파랑', sortOrder: 2 },
                ],
              },
              {
                displayName: '사이즈',
                sortOrder: 1,
                values: [
                  { displayName: 'S', sortOrder: 1 },
                  { displayName: 'M', sortOrder: 2 },
                ],
              },
            ],
          },
        },
        expectedStatus: 200,
        description: '옵션 추가 (4개 Variant 생성 예정)',
      },
      {
        id: 'publish-version',
        method: 'PATCH',
        path: '/masters/{{masterId}}/versions/{{versionId}}/publish',
        service: 'pim',
        expectedStatus: 200,
        description: '버전 Publish',
      },
      {
        id: 'get-variants',
        method: 'GET',
        path: '/variants/masters/{{masterId}}',
        service: 'pim',
        expectedStatus: 200,
        description: '생성된 Variant 조회 (4개)',
        extractFromResponse: {
          variantId1: 'data.0.id',
          variantId2: 'data.1.id',
          variantId3: 'data.2.id',
          variantId4: 'data.3.id',
        },
        responseSchema: z.object({
          data: z.array(z.any()).length(4),
        }),
      },
      {
        id: 'create-channel-coupang',
        method: 'POST',
        path: '/channels',
        service: 'pim',
        body: {
          name: 'Coupang {{timestamp}}',
          site: 'coupang',
          type: 'MARKETPLACE',
        },
        expectedStatus: 201,
        description: '쿠팡 채널 생성',
        extractFromResponse: { channelCoupangId: 'id' },
      },
      {
        id: 'create-channel-naver',
        method: 'POST',
        path: '/channels',
        service: 'pim',
        body: {
          name: 'Naver {{timestamp}}',
          site: 'naver',
          type: 'MARKETPLACE',
        },
        expectedStatus: 201,
        description: '네이버 채널 생성',
        extractFromResponse: { channelNaverId: 'id' },
      },
      {
        id: 'create-channel-product-coupang',
        method: 'POST',
        path: '/channel-products',
        service: 'pim',
        body: {
          masterId: '{{masterId}}',
          channelId: '{{channelCoupangId}}',
          name: 'Coupang Product Name',
        },
        expectedStatus: 201,
        description: '쿠팡 채널 제품 생성',
      },
      {
        id: 'create-channel-product-naver',
        method: 'POST',
        path: '/channel-products',
        service: 'pim',
        body: {
          masterId: '{{masterId}}',
          channelId: '{{channelNaverId}}',
          name: 'Naver Product Name',
        },
        expectedStatus: 201,
        description: '네이버 채널 제품 생성',
      },
      {
        id: 'create-listing-coupang-v1',
        method: 'POST',
        path: '/channel-listings',
        service: 'pim',
        body: {
          variantId: '{{variantId1}}',
          salesChannelId: '{{channelCoupangId}}',
          channelItemId: 'COUPANG-V1-{{timestamp}}',
        },
        expectedStatus: 201,
        description: '쿠팡 Variant 1 매핑',
      },
      {
        id: 'create-listing-coupang-v2',
        method: 'POST',
        path: '/channel-listings',
        service: 'pim',
        body: {
          variantId: '{{variantId2}}',
          salesChannelId: '{{channelCoupangId}}',
          channelItemId: 'COUPANG-V2-{{timestamp}}',
        },
        expectedStatus: 201,
        description: '쿠팡 Variant 2 매핑',
      },
      {
        id: 'create-listing-coupang-v3',
        method: 'POST',
        path: '/channel-listings',
        service: 'pim',
        body: {
          variantId: '{{variantId3}}',
          salesChannelId: '{{channelCoupangId}}',
          channelItemId: 'COUPANG-V3-{{timestamp}}',
        },
        expectedStatus: 201,
        description: '쿠팡 Variant 3 매핑',
      },
      {
        id: 'create-listing-coupang-v4',
        method: 'POST',
        path: '/channel-listings',
        service: 'pim',
        body: {
          variantId: '{{variantId4}}',
          salesChannelId: '{{channelCoupangId}}',
          channelItemId: 'COUPANG-V4-{{timestamp}}',
        },
        expectedStatus: 201,
        description: '쿠팡 Variant 4 매핑',
      },
      {
        id: 'create-listing-naver-v1',
        method: 'POST',
        path: '/channel-listings',
        service: 'pim',
        body: {
          variantId: '{{variantId1}}',
          salesChannelId: '{{channelNaverId}}',
          channelItemId: 'NAVER-V1-{{timestamp}}',
        },
        expectedStatus: 201,
        description: '네이버 Variant 1 매핑',
      },
      {
        id: 'create-listing-naver-v2',
        method: 'POST',
        path: '/channel-listings',
        service: 'pim',
        body: {
          variantId: '{{variantId2}}',
          salesChannelId: '{{channelNaverId}}',
          channelItemId: 'NAVER-V2-{{timestamp}}',
        },
        expectedStatus: 201,
        description: '네이버 Variant 2 매핑',
      },
      {
        id: 'create-listing-naver-v3',
        method: 'POST',
        path: '/channel-listings',
        service: 'pim',
        body: {
          variantId: '{{variantId3}}',
          salesChannelId: '{{channelNaverId}}',
          channelItemId: 'NAVER-V3-{{timestamp}}',
        },
        expectedStatus: 201,
        description: '네이버 Variant 3 매핑',
      },
      {
        id: 'create-listing-naver-v4',
        method: 'POST',
        path: '/channel-listings',
        service: 'pim',
        body: {
          variantId: '{{variantId4}}',
          salesChannelId: '{{channelNaverId}}',
          channelItemId: 'NAVER-V4-{{timestamp}}',
        },
        expectedStatus: 201,
        description: '네이버 Variant 4 매핑',
      },
      {
        id: 'get-channel-products-by-master',
        method: 'GET',
        path: '/channel-products/masters/{{masterId}}',
        service: 'pim',
        expectedStatus: 200,
        description: '마스터의 채널 제품 조회 (2개 확인)',
        responseSchema: z.array(z.any()).length(2),
      },
      {
        id: 'get-listings-by-variant-1',
        method: 'GET',
        path: '/channel-listings/by-variant/{{variantId1}}',
        service: 'pim',
        expectedStatus: 200,
        description: 'Variant 1의 채널 매핑 조회 (2개 확인)',
        responseSchema: z.array(z.any()).length(2),
      },
      {
        id: 'get-listings-by-variant-2',
        method: 'GET',
        path: '/channel-listings/by-variant/{{variantId2}}',
        service: 'pim',
        expectedStatus: 200,
        description: 'Variant 2의 채널 매핑 조회 (2개 확인)',
        responseSchema: z.array(z.any()).length(2),
      },
      {
        id: 'get-listings-by-variant-3',
        method: 'GET',
        path: '/channel-listings/by-variant/{{variantId3}}',
        service: 'pim',
        expectedStatus: 200,
        description: 'Variant 3의 채널 매핑 조회 (2개 확인)',
        responseSchema: z.array(z.any()).length(2),
      },
      {
        id: 'get-listings-by-variant-4',
        method: 'GET',
        path: '/channel-listings/by-variant/{{variantId4}}',
        service: 'pim',
        expectedStatus: 200,
        description: 'Variant 4의 채널 매핑 조회 (2개 확인)',
        responseSchema: z.array(z.any()).length(2),
      },
    ],
  },

  {
    id: 'CHINT-002',
    name: '채널별 가격 차별화',
    category: 'PIM > Channel Integration',
    validation: '동일 Variant가 채널마다 다른 가격으로 판매되는 시나리오',
    steps: [
      {
        id: 'create-master',
        method: 'POST',
        path: '/masters',
        service: 'pim',
        body: {},
        expectedStatus: 201,
        description: '상품 마스터 생성',
        extractFromResponse: { masterId: 'masterId', versionId: 'id' },
      },
      {
        id: 'update-version',
        method: 'PUT',
        path: '/masters/{{masterId}}/versions/{{versionId}}',
        service: 'pim',
        body: {
          name: 'Price Differentiation Product {{timestamp}}',
        },
        expectedStatus: 200,
        description: '제품 정보 설정',
      },
      {
        id: 'publish-version',
        method: 'PATCH',
        path: '/masters/{{masterId}}/versions/{{versionId}}/publish',
        service: 'pim',
        expectedStatus: 200,
        description: '버전 Publish',
      },
      {
        id: 'get-variants',
        method: 'GET',
        path: '/variants/masters/{{masterId}}',
        service: 'pim',
        expectedStatus: 200,
        description: 'Variant 조회 (1개)',
        extractFromResponse: { variantId: 'data.0.id' },
      },
      {
        id: 'create-channel-coupang',
        method: 'POST',
        path: '/channels',
        service: 'pim',
        body: {
          name: 'Coupang {{timestamp}}',
          site: 'coupang',
          type: 'MARKETPLACE',
        },
        expectedStatus: 201,
        description: '쿠팡 채널 생성',
        extractFromResponse: { channelCoupangId: 'id' },
      },
      {
        id: 'create-channel-naver',
        method: 'POST',
        path: '/channels',
        service: 'pim',
        body: {
          name: 'Naver {{timestamp}}',
          site: 'naver',
          type: 'MARKETPLACE',
        },
        expectedStatus: 201,
        description: '네이버 채널 생성',
        extractFromResponse: { channelNaverId: 'id' },
      },
      {
        id: 'create-channel-11st',
        method: 'POST',
        path: '/channels',
        service: 'pim',
        body: {
          name: '11st {{timestamp}}',
          site: 'other',
          type: 'MARKETPLACE',
        },
        expectedStatus: 201,
        description: '11st 채널 생성',
        extractFromResponse: { channel11stId: 'id' },
      },
      {
        id: 'create-channel-product-coupang',
        method: 'POST',
        path: '/channel-products',
        service: 'pim',
        body: {
          masterId: '{{masterId}}',
          channelId: '{{channelCoupangId}}',
        },
        expectedStatus: 201,
        description: '쿠팡 채널 제품 생성',
      },
      {
        id: 'create-channel-product-naver',
        method: 'POST',
        path: '/channel-products',
        service: 'pim',
        body: {
          masterId: '{{masterId}}',
          channelId: '{{channelNaverId}}',
        },
        expectedStatus: 201,
        description: '네이버 채널 제품 생성',
      },
      {
        id: 'create-channel-product-11st',
        method: 'POST',
        path: '/channel-products',
        service: 'pim',
        body: {
          masterId: '{{masterId}}',
          channelId: '{{channel11stId}}',
        },
        expectedStatus: 201,
        description: '11st 채널 제품 생성',
      },
      {
        id: 'create-listing-coupang',
        method: 'POST',
        path: '/channel-listings',
        service: 'pim',
        body: {
          variantId: '{{variantId}}',
          salesChannelId: '{{channelCoupangId}}',
          channelItemId: 'COUPANG-ITEM-{{timestamp}}',
          channelPrice: 25000,
        },
        expectedStatus: 201,
        description: '쿠팡 매핑 생성 (가격: 25000원)',
        extractFromResponse: { channelItemIdCoupang: 'channelItemId' },
      },
      {
        id: 'create-listing-naver',
        method: 'POST',
        path: '/channel-listings',
        service: 'pim',
        body: {
          variantId: '{{variantId}}',
          salesChannelId: '{{channelNaverId}}',
          channelItemId: 'NAVER-ITEM-{{timestamp}}',
          channelPrice: 27000,
        },
        expectedStatus: 201,
        description: '네이버 매핑 생성 (가격: 27000원)',
        extractFromResponse: { channelItemIdNaver: 'channelItemId' },
      },
      {
        id: 'create-listing-11st',
        method: 'POST',
        path: '/channel-listings',
        service: 'pim',
        body: {
          variantId: '{{variantId}}',
          salesChannelId: '{{channel11stId}}',
          channelItemId: '11ST-ITEM-{{timestamp}}',
          channelPrice: 24000,
        },
        expectedStatus: 201,
        description: '11st 매핑 생성 (가격: 24000원)',
        extractFromResponse: { channelItemId11st: 'channelItemId' },
      },
      {
        id: 'lookup-coupang-price',
        method: 'GET',
        path: '/channel-listings/lookup',
        service: 'pim',
        queryParams: {
          salesChannelId: '{{channelCoupangId}}',
          channelItemId: '{{channelItemIdCoupang}}',
        },
        expectedStatus: 200,
        description: '쿠팡 가격 확인',
        responseSchema: z.object({
          variantId: z.string().uuid(),
        }),
      },
      {
        id: 'lookup-naver-price',
        method: 'GET',
        path: '/channel-listings/lookup',
        service: 'pim',
        queryParams: {
          salesChannelId: '{{channelNaverId}}',
          channelItemId: '{{channelItemIdNaver}}',
        },
        expectedStatus: 200,
        description: '네이버 가격 확인',
        responseSchema: z.object({
          variantId: z.string().uuid(),
        }),
      },
      {
        id: 'lookup-11st-price',
        method: 'GET',
        path: '/channel-listings/lookup',
        service: 'pim',
        queryParams: {
          salesChannelId: '{{channel11stId}}',
          channelItemId: '{{channelItemId11st}}',
        },
        expectedStatus: 200,
        description: '11st 가격 확인',
        responseSchema: z.object({
          variantId: z.string().uuid(),
        }),
      },
      {
        id: 'get-variant-listings',
        method: 'GET',
        path: '/channel-listings/by-variant/{{variantId}}',
        service: 'pim',
        expectedStatus: 200,
        description: 'Variant의 모든 채널 매핑 조회',
        responseSchema: z.array(z.any()).length(3),
      },
    ],
  },
];
