export const WAYBILL = {
  CUST_ORD_NO_PREFIX: 'AY',
  PENDING_ATTEMPTS_CAP: 5, // pending unknown_outcome 지속 시 자동 abandon 임계(§8). allocated 는 무제한.
  BATCH_CONCURRENCY: 8, // issueBatch bounded 병렬(§10).
  BATCH_TIME_BUDGET_MS: 45_000, // 동기 배치 시간예산(< ALB 60s). 초과 시 미완건 조기반환(§10).
  ERROR: {
    NOT_FOUND: 'WAYBILL_NOT_FOUND',
    SHIPMENT_NOT_FOUND: 'WAYBILL_SHIPMENT_NOT_FOUND',
    ACTIVE_EXISTS: 'WAYBILL_ACTIVE_EXISTS',
    RECIPIENT_INCOMPLETE: 'WAYBILL_RECIPIENT_INCOMPLETE',
    STALE_MANIFEST_VERSION: 'WAYBILL_STALE_MANIFEST_VERSION',
    NOT_DISPATCHABLE: 'WAYBILL_NOT_DISPATCHABLE',
    STALE: 'WAYBILL_STALE',
    ALREADY_DISPATCHED: 'WAYBILL_ALREADY_DISPATCHED',
    NOT_VOIDABLE: 'WAYBILL_NOT_VOIDABLE',
    TRACKING_EXISTS: 'WAYBILL_TRACKING_EXISTS',
    CARRIER_NOT_CONFIGURED: 'WAYBILL_CARRIER_NOT_CONFIGURED',
    ABANDON_NOT_ALLOWED: 'WAYBILL_ABANDON_NOT_ALLOWED',
  },
} as const;

// 종료(슬롯 해제) 상태. 활성 유니크 WHERE 와 동치.
export const WAYBILL_TERMINAL_STATUSES = ['voided', 'failed', 'abandoned'] as const;
// 디스패치 가능 상태.
export const WAYBILL_DISPATCHABLE_STATUSES = ['registered', 'used'] as const;
